import traci
import time

# Start SUMO with our config file
sumoCmd = ["sumo-gui", "-c", "config.sumocfg"]
traci.start(sumoCmd)

# We assume a simple intersection where 'node_0' is the main traffic light
TLS_ID = "0"  # ID of the traffic light (auto-generated by netgenerate)

def get_simulated_yolo_data(edge_id):
    """
    Simulates YOLO by asking SUMO how many cars are currently on a specific road (edge).
    """
    vehicle_count = traci.edge.getLastStepVehicleNumber(edge_id)
    halting_count = traci.edge.getLastStepHaltingNumber(edge_id) # Cars stopped (Wait time)
    return vehicle_count, halting_count

def dynamic_signal_control():
    """
    Your novel Spatio-Temporal algorithm.
    """
    step = 0
    
    # Run simulation for 500 steps
    while step < 500:
        traci.simulationStep()
        
        # Every 30 simulation steps, we re-evaluate the traffic
        if step % 30 == 0:
            # 1. Get data for the main incoming road (Let's assume edge '1i' is Northbound)
            # In your real setup, YOLO provides these numbers
            density, waiting_cars = get_simulated_yolo_data("1i")
            
            # 2. Look-Ahead Logic: Check the downstream road (Edge '2o')
            downstream_density, _ = get_simulated_yolo_data("2o")
            
            print(f"--- Step {step} ---")
            print(f"Incoming Density: {density}, Waiting: {waiting_cars}")
            print(f"Downstream Density: {downstream_density}")

            # 3. Calculate New Green Time
            # Base green time
            green_time = 10 + (density * 2) + (waiting_cars * 1.5)
            
            # SPATIAL GRAPH NOVELTY: If downstream is backed up, restrict green time!
            # Let's say a density > 10 is considered "backed up" for this small map
            if downstream_density > 10:
                print("WARNING: Downstream full! Preventing Gridlock.")
                green_time = min(green_time, 15) # Cap green time at 15 seconds
            else:
                # Cap at a normal maximum so side streets don't starve
                green_time = min(green_time, 60) 

            print(f"-> Setting Green Time to: {int(green_time)} seconds\n")
            
            # 4. Actuate the Traffic Light
            # Force phase 0 (Green for North/South) for the calculated duration
            traci.trafficlight.setPhase(TLS_ID, 0)
            traci.trafficlight.setPhaseDuration(TLS_ID, int(green_time))

        step += 1
        time.sleep(0.05) # Slow down the GUI so you can watch it happen

    traci.close()

if __name__ == "__main__":
    dynamic_signal_control()